import Head from 'next/head'
import Courses from "@/components/Screens/Courses/Courses";



export default function Component() {
  return (
    <>
      <Head>
        <title>Courses</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <Courses/>
      </main>
    </>
  )
}
